# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - hand_group_controller
    - arm_group_controller

  hand_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default : true
    joints:
      - J5
      - rightTip_joint
      - J6
      - leftTip_joint
  arm_group_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default : true
    joints:
      - J1
      - J2
      - J3
      - J4